apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery-platform
  namespace: staging
spec:
  project: staging
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/helm-charts
    targetRevision: main
    path: discovery-platform
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/discovery-platform
              tag: "0.12.1"
              pullPolicy: "Always"
            replicaCount: 1
            envFrom:
              - type: secret
                name: discovery-platform
            service:
              name: "http"
            env:
              - name: "PORT"
                value: "3020"
              - name: "DEBUG"
                value: "rpch*"
              - name: "URL"
                value: "https://discovery.staging.rpch.tech"
            ingress:
              enabled: true
              className: traefik
              annotations:
                cert-manager.io/cluster-issuer: production
                traefik.ingress.kubernetes.io/router.middlewares: traefik-rate-limiting@kubernetescrd
              hosts:
                - host: discovery.staging.rpch.tech
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: discovery.staging.rpch.tech-tls
                  hosts:
                    - discovery.staging.rpch.tech
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
