apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery-platform
  namespace: staging
spec:
  project: staging
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/helm-charts
    targetRevision: main
    path: discovery-platform
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/discovery-platform
              tag: "latest"
            replicaCount: 1
            envFrom:
              - type: secret
                name: discovery-platform
            service:
              name: "http"
            env:
              - name: "SKIP_CHECK_COMMITMENT"
                value: "true"
              - name: "FUNDING_SERVICE_URL"
                value: "http://staging-funding-service.staging:3010"
              - name: "AVAILABILITY_MONITOR_URL"
                value: "http://staging-availability-monitor.staging:3050"
              - name: "DEBUG"
                value: "rpch*"
            ingress:
              enabled: true
              className: traefik
              annotations:
                cert-manager.io/cluster-issuer: production
                traefik.ingress.kubernetes.io/router.middlewares: traefik-rate-limiting@kubernetescrd
              hosts:
                - host: staging.discovery.rpch.tech
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: staging.discovery.rpch.tech-tls
                  hosts:
                    - staging.discovery.rpch.tech
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
