apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hoprd-operator-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hoprnet/hoprd-operator
    targetRevision: rpch
    path: charts/hoprd-operator
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            operator:
              secretName: hoprd
              secretKeyName: PRIVATE_KEY
              persistence:
                storageClassName: main
              ingress:
                ingressClassName: traefik
                dnsDomain: hoprd.rpch.tech
                annotations:
                  cert-manager.io/cluster-issuer: production
            adminUI:
              enabled: true
            ingress:
              enabled: true
              ingressClassName: traefik
              hostname: admin.hoprd.rpch.tech
              annotations:
                cert-manager.io/cluster-issuer: production
            replicator:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
