apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hoprd-operator-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hoprnet/hoprd-operator
    targetRevision: rpch
    path: charts/hoprd-operator
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            ingress:
              enabled: true
              ingressClassName: traefik
            replicator:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
