apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-operator
  namespace: staging-operator
spec:
  encryptedData:
    PRIVATE_KEY: AgBMd9HR6WbYuZMI8CE6FhT7f7dvrDnsjZG9j5ZC6PmCZK2KgIVotvZMLaW53LRDwo81ss608Ngsp9+YzYLyGYnMjsXKFTK+zGM8Eh3SBJ4e+ciW/r03rZwxqTWnY2HkcbE8u/ewIcDnoAj12UZFyMezy8YKec1hh2XJ412KoWFz8ADeOdosma3DhIo6BGZQSG26lqyr0oIT4T+NmEJ3LUHGmKLKs2qOosL6lS+lISCXbWecmCQDYCf728fY9MQDayxS5TQPebmP5z8/t+kPzgJXUkgPJwK6MDrvjtvCezwNnKBTirJmXkZPeLewxZSifqRWF6lXfGOPz6WzR7RpBkr1PInOGEEm7aUoHe8tIdhN5Se9I+GdhTUMo4yJbsTCDhunw/DcDe9lMDzeQqxK3HV1sJzAQk3rJo7NluC8bml+N0zO1dF73H6LgNnWInMUri/8EgN1mg1SQYZuK7Zhhmt76kcqYxoLCnvpVGN0xXRNEdBai8Ps8QQVU1GeCpmA8b4liG3k0xvUydHjpYpOI9NENcMm2fa9Ib8GHUACL6A/h2iklLJIndo4bU7vNxUxMRjrXiATIyrPeT3JaBEctaCex2wtvcTnhs9pp7nPd9kUcLKRthzA0KCjgdzrOR8keUr4s2kHFaVa4n6UDey3dSI1iVH78VRaHtU4gwyZt0MjEE1zGpyiip2con6ekqJTLd0G3BuaLAhtWZc5soITjmskntpYBIcM39OW3p//XR1hH2NjIQUsvSAbYnmIHB1Pdwn5plNQhikS4lInpzMNIlJqojk=
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-operator
      namespace: staging-operator