apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: availability-monitor
  namespace: production
spec:
  encryptedData:
    DB_CONNECTION_URL: AgCEpwl8HeItNYsCqA+TVXF7Sp0k4LwXk9Njjp7o3hbnpLsGIqXJSdEUgS+5hATGnT4tIMhYXXk4zJGl3t6IQrlbU0iH+u6HbjWEjGtdZN+vtlsHLEsFceXH+5tNLAPw8fZ4TLZK7GjRqoJR73fBEjznzo5ftCj7drCzar+17csY5lk+NCT2q9v8FQ9hZrkgDdQF5WZUo8Q7xUiMYk22NDwz9V147SLM9guMYyKn2l3btyfHrLkuhUjH0+4BIIdc673tN97pG2+qqAzUGdNnVtbv2QqujnpqOjz41dY28jsB8YEd2ECPgJyXKrgduejnfEJi6BfpLzMNhchzNaGiehBtHXwZUi5WIrNAH+Ak6W6bc1mqwS6I04T/rpy5/YrGHF1Gw2pRZMKpe5KhShJNadC1lJdkLDdXXC6KSm2ohia/GSA/jK8F9yTk1mC0sqRRKxQ+zbyUxcn+cB5Nzv95fxsIoIPFCc6Z8XPQ8Akudv+j0S7fD6H7lcUsgb3FfsgrMDG3RM0M8GCIGUJy1vzewNSbbkQ4i5PxfyPFkq2jSfM3ivZVYadhKnKRZ7fEXbYqSNN7OUqNnP92OUun6gacILJJlxSQ45WbOr1TfXPhW/454LiuJBK9XP2UoTPW6Hz0aq8ZLZRbawAhAAEG2EF2526y9qGnxOJoVvhZ6aJH5A4lgUIJ8LYpmbUtoe/OKUV2de9CkwYo2LBxZLXXd8GAebrDEE9cEWx6k2Gb7S+vpKv0fgxrKOgPOH9ESZ6PXbDt+m0SyRWE
  template:
    metadata:
      creationTimestamp: null
      name: availability-monitor
      namespace: production

