apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: availability-monitor
  namespace: production
spec:
  encryptedData:
    DATABASE_URL: AgBa6P9kfqZeR+nveECN3r/PFJyWajcf3XEnpQDrf/abm+9qZ8jKmthi9B9TE2ijJ4RDEERyYVbFEogojNA1uyzKa2zG2yyV2sfI/qM1x0aXm3F7WkwtoieXxHrHjwPolzKcvO1cjN+p60tWSkCB/+TUk0KvMgHTsX8ZqtpBTfc3wIfQwE1g4IDBZiNC+q7ZpKfgdgxZ7Fn1JwT4t0lck7tXYQ4orquJ33vjPqaqoAkdo0NEbZTspygq+z+CUZXDWJbayRwnGxchr9BJZ67qyMkqj9ncoy6NjFgT0rZrn1RRBKdue33j+ZXNdvhiVA71WyFkrncMGSevevkbXK5yXJwpKS8VhBBRNkMqncW4rM9t87nz8lJAIcIpeqSANTIY3qQjdKm2axcN67xhFSDNwjHPL9gNAO5bsLuWTrUMrp28FfkxBI4P+Qe3nL1MXWUnBTZxsiSAOmm7odNYHkAwXujDz2hmmFpru6hHdltUqzyo58CHbRSmrsc2w7pI+AcXM2RBUoHrWinkGGh5AsnImolZcTPQ3fgb3OiHHoUB3efr8cH8sCyk21F7ZZkraDQdvECM2PFdurf3032CXnVl+P4HqCf+/LvDK7czLYVRhAwfS/mTkAAijXpWhClegBUd0sqaOkgQC8NMcWgsEseG/HgmUWH6zkU0A6Vdm3kjKtigF5UpJLhCQjFdCJhEDHi88eS+P064Hk7nmSJPluYcAGB0kdoP5GwubaD1YGpbDBDFtfJyNmz4g7Da/ETwvYTCr6QoCw==
  template:
    metadata:
      creationTimestamp: null
      name: availability-monitor
      namespace: production

