apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: manager
  namespace: production
spec:
  encryptedData:
    DP_SECRET: AgBVQJmQBdXriPKe+X1B25cWemaKsnb6yToJiS2ev+emCrYc/aaM2PGq6+Q1m7WNR5NCnOEDLCivXGWYQXYy0XePif5rv3POSxXdlGvPmJf/xaslGYjSxx+N6Ip/Zkos2th3tw6VZUjRi2x6F4d3DC/XTkpChlDk3zaxf1MfWjcuKDIojkP1tyibdUVkPSAIc6kM3PTMuK6hCF17SP8xmoP/2HgOJwAjbZP/ZmxujtVeQbaZtff2jLosabGcJF+ceC3eb0hiiGs5hn+s4o/rYi/v71u5q9mUM2gVkRC33JJLOW/NRZx7jEybdTA2GBx3a2B1gWcHtfFhKaFMq8CZJNktXkna7bMZcy36IHzEfP892zjt8Lkj19JJUDYp55Xgh2KgBc8et4qaVS0bT06bBZch/FoCoTupFmOFwzUuVWBh3tEsd7SbgFywNbgAX9clf8vbj7wRWPhu14F660EVoQUHz1dnGCepWwIs78UR1OlL8o/+Q39mgxQ3LxkUcqCHTJ2lVzTxKCQw4Del+F+GOCiu6LSA8kHIyeW4HW64AoiWIfiWB/o4F/Io75TWCZfkO5WCli69gKn6E3flsAY//J2Kj42S19lLK33qRB5RNQT02OHofO1ToIEkev1YLwlrursva8nRg2/p022CKpBI3h6T9/vMnFtSa1eywTmwjcGsjNYb5XflCvMSOszcF2Nfm2psI5PqWMKpt5CsY6LCM2M8
  template:
    metadata:
      creationTimestamp: null
      name: manager
      namespace: production
    type: Opaque