apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rpc-server
  namespace: production
spec:
  project: production
  source:
    repoURL: https://github.com/Rpc-h/helm-charts
    targetRevision: main
    path: rpc-server
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            resources:
              requests:
                cpu: 1000m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 512Mi
            service:
              port: 8080
            image:
              repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server
              tag: "0698001"
              pullPolicy: "Always"
            replicaCount: 1
            envFrom:
              - type: secret
                name: rpc-server
            env:
              - name: "DEBUG"
                value: "rpch*"
              - name: "RESPONSE_TIMEOUT"
                value: "10000"
              - name: "DISCOVERY_PLATFORM_API_ENDPOINT"
                value: "http://production-discovery-platform.production:3020"
              - name: "PORT"
                value: "8080"
              - name: "DATA_DIR"
                value: "app"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
