apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exit-node
  namespace: argocd #TODO - for multi-tenancy, this can be changed to another ns.
spec:
  generators:
    - list:
        elements:
          - id: "1"
          - id: "2"
          - id: "3"
          - id: "4"
          - id: "5"
          - id: "6"
          - id: "7"
          - id: "8"
          - id: "9"
          - id: "10"
          - id: "11"
          - id: "12"
          - id: "13"
          - id: "14"
          - id: "15"
          - id: "16"
          - id: "17"
          - id: "18"
          - id: "19"
          - id: "20"
  template:
    metadata:
      name: "exit-node-{{id}}"
    spec:
      project: production
      source:
        repoURL: https://github.com/Rpc-h/helm-charts
        targetRevision: main
        path: exit-node
        plugin:
          env:
            - name: HELM_VALUES
              value: |
                image:
                  repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/exit-node
                  tag: "6b5ca56"
                envFrom:
                  - type: secret
                    name: exit-node-{{id}}
                  - type: secret
                    name: hoprd-node-{{id}}
                env:
                  - name: "HOPRD_API_ENDPOINT"
                    value: "https://hoprd-node-{{id}}.production.hoprd.rpch.tech"
                  - name: "DEBUG"
                    value: "rpch*"
                  - name: "RPCH_IDENTITY_FILE"
                    value: "/mnt/identity/.rpch-identity"
                  - name: "RPCH_DATA_DIR"
                    value: "/mnt/data"
                securityContext:
                  runAsUser: 0 #TODO - this is bad
                  runAsGroup: 0 #TODO - this is bad
                ingress:
                  enabled: true
                  className: traefik
                  annotations:
                    traefik.ingress.kubernetes.io/router.entrypoints: websecure
                    cert-manager.io/cluster-issuer: production
                  hosts:
                    - host: exit-node-{{id}}.production.rpch.tech
                      paths:
                        - path: /
                          pathType: ImplementationSpecific
                          port: 3001
                  tls:
                    - secretName: exit-node-{{id}}.production.rpch.tech-tls
                      hosts:
                        - exit-node-{{id}}.production.rpch.tech
      destination:
        server: https://kubernetes.default.svc
        namespace: production
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
