apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: latency-monitor-staging
  namespace: staging
spec:
  groups:
    - name: latency-monitor-staging
      rules:
        - alert: LatencyMonitorHighLatency
          annotations:
            description: >-
              10% of all successful RPCh request latencies (quantile Q90%) have been above 1.5 second for 10 minutes.
            summary: Latencies are very high.
          expr: rpch_latencies_success{quantile="0.9"} > 1.5
          for: 10m
          labels:
            severity: warning
            environment: staging
        - alert: LatencyMonitorHighFailureCount
          annotations:
            description: RPCh latency monitor identified {{ $value | humanize }} failures for 3 minutes.
            summary: Failed latency request count is very high.
          expr: increase(rpch_latencies_failure_count{namespace="staging"}[30m]) > 1500
          for: 30m
          labels:
            severity: critical
            environment: staging