apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: availability-monitor
  namespace: staging
spec:
  project: staging
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/helm-charts
    targetRevision: main
    path: availability-monitor
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/availability-monitor
              tag: "0.7.5"
              pullPolicy: "Always"
            replicaCount: 1
            envFrom:
              - type: secret
                name: availability-monitor
            service:
              name: "http"
            env:
              - name: "PORT"
                value: 3050
              - name: "DEBUG"
                value: "rpch:availability-monitor*"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
