apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: availability-monitor
  namespace: staging
spec:
  encryptedData:
    DB_CONNECTION_URL: AgA1AlPxTzss1X9A4N1FH8/LNuxPaWWZCQk70Wh5rVdtL7XPHH5iyl5hX6AMjrsB04xEFtq/VyzXwlfrMVnS0yM5qM/VZyEhlnIwdkX3SGYvYArWPR/ldCzD8Sa2RHZ2dYVz1SNk8CgkRxb+fg33mPWgkOqIrS9w19mNzsg7LAmZ2Nlb+8NDfsVK3WUKH5Wam5q8jsxTbX5DNfprynCDWyIFE1FuqYWsygGfn8/GkoJjtkcHf/Wkog2prD5gSDUjrBSuFkIU5cv+byEkiKZuM6jo5E57l+q/Bo3T3bWwj03KWwqvtdLMIpksFetZdgyITcmxcjtHhFeiSY4M9KpHEPzI8iGOl+QPnnumO01nZtdZ1px8O679OSYfFtuI6PF338uitlWmjy5+P9hnWjR3C412f4Jt3Ep2llsQ9wdAVCtbXe/Rd4xyglFYIEBsbxBzEjKhjaC4dbkGj3UO4R0/yUrCl5qtfFtj2kwD307wiQ6dfJt87Ni0Q7XXUhnRs3X6RBJZRi9S1GCPrweYbD6VYtdZaZ3b7vPTfd1UmWAr6pOhRZZ5Bl8EYDPY5t/H5qZ02zENzHeNcZR7yH8HhGkVmS2SnAg1jIg0WkCAcC+j9UQyAB5HKHcjMG9H4h1Bzv+ORBBGPb7rGd1SP/c8qm2awcR0jBfCTl8NjvnJSAuxDz9i0ocbKR+6qt/jSMYu/Wj3d4766f3bRgute7BItTg/Ckqq129FJU2/CS4kD5S4SefrASaTpp1LJPz/HSJDZyJDa8s4ZOXv
  template:
    metadata:
      creationTimestamp: null
      name: availability-monitor
      namespace: staging
