apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: availability-monitor
  namespace: staging
spec:
  encryptedData:
    DATABASE_URL: AgC3mfwasPjoYyuwcows2NAK/7CVIT+3IItJzuXSWz6CBZvjAmlp5C7ft7MTGlc5/KE8Hu7F4CzsdyGFbMCF4HqG0bSTDh8Osjdng6ONgrvU50Eooap4mFRqPpPSs36OjJ90INMoK1xI+iOQLXPfgrhU3IxhQ9BGS+C3IpK2lu1f+mx3YQAAlxz4+zt2rBTNQSSCr1GH/iabJ4RwOtLZXfAJ1RyShTX6TZEMnoBOAjPph+DkNmzujV+9f5yNUMZnNfhbw4mtFDj9/t/+RSk03QNrmgPRG4dyvew2PMXiVa5eyKt0ODI0pQTRw47562mj24kPqJF206NGcTqPKd/gO0JT1gdzhVeRkJr69ijpJ7gUEN0CMyeHxUfO3Jkv3qIqJomoLFJe77hbtUG+ZtO0DbL9/+p0bA4DxpK31p9k6o1MErFMdyV937vv1YwCjqD3PLR/QWD12Z4SUpgnw/TdQvZwcqr23b+7SFN/Yb1V5HC4Dfi/mZjipfcNHnyDmXv8iRCkecBDRiXjiZvw99iIpk5LFJ6E6tOZ5f3Pw1IKCFxEqh3v81BtBeejgSwrhYlGqR0BPxDtmp1G7NB5IRvIYAyBD1BjRxNdu5c5sZiDNsltooYAyOGwPWt5JS74eV2grTJu7D9ZBNhiQd5KXAKkG4rI3NGJf81AhdowIJga/McbH4G5X1txCh0x3+BdCxehyaQmvWtrVLb3le1ErIIfKXFCccoQRmokXfM4NUuoudAc+18fb0xXjU9/D0WYlNw=
  template:
    metadata:
      creationTimestamp: null
      name: availability-monitor
      namespace: staging

