apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exit-node-4
  namespace: production
spec:
  encryptedData:
    RPCH_PRIVATE_KEY: AgBiTigIMy7XLkAkaB0gloOtH1DqLvVPf2B0f5l+46QWiLOD0fR6SWE/wrigYq30HjQGWfQwrnpWPFvp0YcsJ/KcBU+3ST8MwNrDjB9c3p4IPrbkbxjtFFnz6Lv2ruR3OpqKoAvKa/9O5gIisPvm44qaVUCSINiKjrIqtCvhp7eYz23v6FdpnS7z13DjiGwjIv4rKmElZhRiWbz5b6F+MDLWu77UdHpEQuo7aiWHk4kmqnIpAJgeSVIE7r+I4URFgm9VKYWpUmdOoo7eXijQ3+eznpnv5Xb7zK1HxAwkbUG9um+Xgw/XTcDYhsmT5JRGZMGiVHMqpuDwo5Thtu8a8GiWy2KAJsa3WRZ+9jjEBl32iz/jWt9+Gc2TK3ZxiskcRhv1hQmxDEUqmnpaausH7E6ZeODrmqtLYrFwJzWDEO8Thd8+h+TfLuMtEeEydAYxSX/Ks56pj9uOEqNEKweilOAclFfs0EceS85NmSNRD9gAhsLHzNTIX+IaYeXeZ7uzEH3q/gIftR01Qoj1rcj3DvfhAcoFkdGzgIk4McQDgcPKHcBasASU1zejMY+tK3cXSYMPcm1nfoK9rCUJN//xtpXeRQ6HnnGhffREmBknfhAb1puPguLOX9gSpRfXqOhuTranSlW3gd1F5A1WmIx+bng4pvA1SvhejCfNQaqCo5SHQE8Dj7Em3bmujvZHKC62SyYJTytkoPM1MIAWnsxkPbnggKLJAyrWXjqMuSstitkRwE80SL75q5tjnKWaL+ky3Wy0k4Sn+AhcIo3CocVDGOlp9Zo=
  template:
    metadata:
      annotations:
        address: 0x5d3c5c3Fd989f9Cbc06F4a769dC73dCC7F31b68c
        public-key: 0x0219afdbcb681ad0d1814b86229fbefd2a77ed0879ad4d403e657e80aa6275c262
      creationTimestamp: null
      name: exit-node-4
      namespace: production

