apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exit-node-18
  namespace: production
spec:
  encryptedData:
    RPCH_PRIVATE_KEY: AgBbAJ/5W7ctdJbGvp63AAKYH0FxOI2aBLMderibWTQN2pzxKdasetnqJ4k8k9THERZeNhDrpxHfigtiV6EAI5hv3J3/FPjhMJaCuCcyHDs4jNj3au41oXzB9LETkPPmAwHbWIMyEF/2puF47J0VwBe3GAiTbd2ietLoa7CNN0J/DxW/Ps5ThZEmwyIp4OCbK+d6GiOQvtmTeUmnyFNtBsfN+caNfP5Shwxmg9tsMLquOY4SGLkLsfnvgrWSKRHXVFJyCrI3ZvXM3cVFgXygrkXlZt7KkDqYupEoODZtVI+VaHGI6Kq9+f2wSXSxKBputB0Zt2VG9oNs5fvqLoRhjVcsgJ9XknNWhPgSE0tW4H2IOWVMRjR8LBo0DMJoIbu1oRK5qlTIg5099xOWIKkY+bn/IxxCiyDyw2nIpS/i09L+EQvRiUHoiMrzZM09NcW+SK3HDVb+W906mdq9DheDa9m9OzT3J7frdW7RKsg2FTSWna81oGoViBHxoicsHV3VsKm+hS7YJK585VeXhMZs6P0CPnf/5EG82upQ0GR2dkapnT2rpXIASPJPnmMJgO/MxE9lzmpMqN59yg3OQQaFT/VwtXec0374HoVSUt2XPsVCEY7vjEy7ijmwhctSwTOZ9jLBY8BbRlkAuaojnM8PnR3MOZvgVUDTNFHOihxhI3KyJsS2wDZgx+1l39ns5fjf9vQcqrvhVMHtcKjI1eLEtgodmY698kOnJFC4FSarELdK/19FLVIzyqe7a7Gqah5HCTxzhZjZ1y9CtJsJ/SJCEt25cpg=
  template:
    metadata:
      annotations:
        address: 0x4c447c989958dd355b980d2deff280b6b6dd80f7
      creationTimestamp: null
      name: exit-node-18
      namespace: production

