apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exit-node-10
  namespace: production
spec:
  encryptedData:
    RPCH_PRIVATE_KEY: AgAwwpLq+KAjrDSDfQYibdQM2qgATro2l8Ggjlqkqm2PAkyfdSPusk67cdjNV0xjenlQG/Hcxsc+8wJVRVflMRGL6NL5hqRneVknbipXywBxKMD0wydokoCZtGKPOMGidsB7To8j0XddXz4OxJxn69/USIBTrfTynVPxtG3ffDpZhDp5IArg8W3/QR7r6veDY9AQvOsImHXgpFSQXMnjK75J1wmT/UkBtBzU4/ggB/dDJianb+WR7nMkjn3lTb57a73BMZ++9z5LKip6vDGdueaamMjtz0yk3luJ8uJ12H5NkO+QCd8Wgq3Z6n8CNm5L4hSFDaK3f74w9P5MVktavnDLWgCo/9Ez6ly9Fyq22n2frdO9J5C6AzvrQZiLMNh5yg8r6jb0HtEg+fIoqxGuNFUiSILO/ThWEXe5V3IkitCVzNcwm8qcnd303ZpEoKClQxjZmuS5uSbn1OR+X6AsMQYQUvEVQ0GFK+0/M9QspEKkoJ6psWmUHn81pjclI+5ypQ3rXBoyueh96T5q3NFTT9o5JRLm1rYDCNCdmzFLqEfEEVDYWK6uIi0irhb5XaYUawTK038qNcRdJqKk/5k6RWffM+GWcY5/trunQS1YtnxuL+ocHM+dU71VH5mSQYfVwTAuIx95xtCOvMXf/zZn26++N/MRMy7VYs9DhRBr/EdgEqzOpiAcQBwZWPbm8LhcluUjheZ5unRMSMRnb6JmZm8sa+N0VbVylpK5139Hx+rg98OgngvrWeDIKGQgOSz7Qqj+lSALYJ1Q6JjdQp6ZOHLsWTk=
  template:
    metadata:
      annotations:
        address: 0xCc639a4a277b03fAD9ECBd3e39c25972A0519e3e
        public-key: 0x02b380e5e23b6ae009f3bc0951a5893be53b2c59401bb9b0a268a6d7220b7ad6db
      creationTimestamp: null
      name: exit-node-10
      namespace: production

