apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exit-node-15
  namespace: production
spec:
  encryptedData:
    RPCH_PRIVATE_KEY: AgCKp9hmdHqYuH1zO0MufGxQ9rWOxqgwcDft5GwSMEa7SuhaqBhqyu1k2TYPYvHxxaRDLKojGDDT4tYK8AtgVRPDQYQgd9NfU9+2u0pQpSNPySXNow1EQmM7eZYZDaskQGj+qeo9CMkF5qsfXhacUS5ieccU52YH1wnMF5hj4JI4SxyPiZTPYhKKXHwKe3J5rwIhfp8chS235VuBonHOWlXf8gFwkc/IsYptpwetseg+TFZm35EModQVeMDU1VppEa0UVp4Y/9lN2ykSUom2hXGPMzHzMc1fgA2P1oAJVbPqeV098rT41AATjgI7VFvZkIQHefg8Pwu30iQs3ZbagUl9xh09oCEbpJ4+vocxVlx+6Jzi5tqbM5aCTc+bM9FHDvrjUPXnbWDvD3ZS/kOAY1qMdIyGM/paUBg+Du/Xqkp6xVEZpLt19RG6ff6GncUs5yP/mxFBSNcqb3mh8lPa0vVnqG3iDnu+5U7ED3gJFDSQSQEVKBWh59z4Zb3QpPRFTDHSxvI0V24pB3mnEKCECFoJM09i84TuY191Wea1gZcBKhai3gagK22rdbyvhmXUEs3BKcevg1RWXW+GUJypTe2X9Qm1kTIn0AQBln/P4vVipVy4u+kuB9H8pbXXA6kUVkHWRlCi2XnCb7vh4X9NrzSNABq0kZGUHLbJJBfiFs/qKxK6i8Db/gEnFkV4GDxyxRomvKorjiZlDoocv6sVSyGTY4i+oKZhcTfmGo8y5KLQ5xBgqsE5nKN/xTjDfhYNcvC3YFMmcZPGbUjL8Gmdb0dGKYk=
  template:
    metadata:
      annotations:
        address: 0x45f56a81edda0347795eeaebf301430cf19e52d5
      creationTimestamp: null
      name: exit-node-15
      namespace: production

