apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exit-node-3
  namespace: production
spec:
  encryptedData:
    RPCH_PRIVATE_KEY: AgA+56Y0hWSKrV9LtIAzPVjZh2YgMs+K5FCZGEiLm5YaBY+eQUNSDe3AxduHhgUhUgken/o18IU/qrbRqPZZhIFRMVEcG0YO9W0XRDrhZ0MxS410do75Nd5RZKXNTkp26M/etiTYZxd+qrg7miCDQvlZgw0EmULbINL7vL2JzjDySKQJPEJ6gp8uCifZGcujSgUKBbXh+SDAwLre49IN7lqtMK/GUeA9eiv+9O2fBqBCz4syLptcCzITJa0RaVkXWNUZ62cCBHzvvqohdElpQrG1dqpPZKdyYC18raxLfmHFsL8QhhJHlFHdAWgrqwyDWWo+uXHhOFrRxAI11gAHiYZ62+AleE0uui9+vRUie3nMTtnu/BN9U0ZabnYXLPMfNQkThu+jak4ll95EfBZA1yLoNtw08PSE5z++N2pVH+U0QMDabq6oXd0DLklwabEDgagdbgFPG5wr/5OWgaMaPYcIILSLiNW0oFHNavotiZVMrXmonHzOV07USMBbTGj3X8xMHTjOh7t9PMjNLQ126M7hsMXPplaJIfJ0qaicf1eCeBtuGIOEOegf63wo47kcwnPMXWcESaG9EK99TOzoyAiKCoU+yDW0M+DvzFezyYw32skvnTRsM5mmlUfYGL44ojxxSnfQyJy/qcgRUEJrjIozgtL+/CtfaydSSAxCCljylP9Fma4HX+ervQf7e+wDrq/7mlCJvUu+5xxr6giDUeFiUaXXWMvVu1IsvQucQlBAeLVvEaNFBP+hi9xx7KsuRwFiZFO/LFgMy11La/z67J3xq3c=
  template:
    metadata:
      annotations:
        address: 0xb56747ee13e222c40a0a4c2418d0a37bc44186e5
      creationTimestamp: null
      name: exit-node-3
      namespace: production

