apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exit-node-11
  namespace: production
spec:
  encryptedData:
    RPCH_PRIVATE_KEY: AgAxWez01mPB+BugGVnc7TfO4+c8UCENTkgUB3zucwtcZa0wYxdJKCamfhkhJh6EuzXbRHF8EjZsML+QmZp3pWHH0Un+2y9vv2PRaoWhYzNfbPox057LZcIb1J83UfhgiV4a/G+yEL1F3yu3X5nMm6M4TDYuk3qjdezOUeBWbmzouZYGG9PMZPZboH9rGywaydYBcClxH5cfR3lZ+E7v7BoIayUN8I7snh7A0iv67IdlroffucR91sRpjeb7A51nQIqXRuCcUTtrbO/kXYMvJMPzQQ5HKhaFvcUSACHGpxiNHzduTOQAjvceeyjnfChIyyLebkVXvJOV94vXurC+ZX8S9klda2QPnsKgsV7KDMaQqQfmdBlUL4Z3gIeh9cF4n/YLgdjtWLE6sDFTQTgECckEflBdNQVoDwctB8qxUF4D4sR2HgTA1Ek8xiq3bWuNPADYYTissVvVtcmKNR9G25xibuqCsZpkXdDj7iGNgRQk5Wye9o3ZtEXJ5t6GpMlTNNSUsYqtMsXC9T1/QK2MJn7R603LxXhFDTF9xehZfTxCKyPFf/VH6A5IBvkxTa9C8l6Z0q9L109ZL47L3vt3KN2TXB4MDlMo+JMCNftS38B1r++UfRheXcqWzLnoAr91Sq8FLXIx92D3rU7rII45H7N7a796ORyUjx0wnNVklBMu9eCaEIHO/UTs4XqdN4gt0I/IR4aT/OJR6J2IQSIPZo12n9eA9NlKxLTiq6EGKYfvJDxqaDI3aYs5hQsenEc9SIkVx7GhD15erPMbsk9oih/Mf38=
  template:
    metadata:
      annotations:
        address: 0xCfe75595350c754141A952D59b15D60c10dE2A62
        public-key: 0x034a79aa84697f1b29f4c0e863d35e2f96df7ca88be12c6b7e10ab309348f7c5ce
      creationTimestamp: null
      name: exit-node-11
      namespace: production

