apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exit-node-13
  namespace: production
spec:
  encryptedData:
    RPCH_PRIVATE_KEY: AgB8qa2eWS53goIfkhEl1XFY/rZtGbmjVwleOeE1GJZ7Y0j0CYGoIuH9YCWcOypNp007Zt1lFtm8dGHyLfWjkxquYTTbq7i7ftZkhfMdmyG3GIHKOC2XhvAdM430bRs/3W5PAoSJ1F7Vpwh1GUfGJqkeAHP3QyY8bz1O/oZCxrYlBgBkxTxv+Rk/xcqmDtsnsPqeUiO9DDX724hBt5hCkJ2qU4EtMRMbB3TJ3njS3Br2lxl91XOmStSUO19atkOBu4E7FxGK1pw5i8xdD+U2kh/AlpcRO7Pfj62JNX7dOLYMtdFOQBEwKwKCoDn5iqmh12Pny93rcVQJhXxDSmbxbX/7lL7HcAcCboDckTbZP1PN1w27hHoOB+AQgBYLUtajz54l/CBQaSHJjZ2gcU3Ep1Uzix9YwUukW8TfX7UpvPoFIhHGmyHdxU1rSgP1TSkw91PmE2jgFAIq5QZ5HfcWGKdPDkmJ14DrWhHPMfMyoxLUP7BeXyG0w1EdNU5wTUV788mf446IgTNDISxyynkaqJsQy+QyTfoQ7NJiCGz5u7c0Ij2VQop1RsQOQjiG2JsQPcHg7LD6iwtsnvoaCBRAfd89JuO+Aps3fzpIWzj1mpUXOh88eLmWdVmsWa/AVsQynU6pcEMR5P3odq5eE7seO2zXw59cjHNmvSRgtyvD01sc8+IJS49b4PodLv74BpAKuzET9Sx8LI3dFMVGTo5NCx8cV5E5qqoboPPaDsdSIZXeJsXDigIwg3jcigSoaBXXkV78KlnK45HKAsDB6bviZsOJb6c=
  template:
    metadata:
      annotations:
        address: 0xd728f0f433a3eec2be749ff3cde172540a445c86
      creationTimestamp: null
      name: exit-node-13
      namespace: production

