apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rpc-server-zero-hop
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://github.com/Rpc-h/helm-charts
    targetRevision: main
    path: rpc-server
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            resources:
              requests:
                cpu: 1000m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 512Mi
            service:
              port: 45750
            image:
              repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server
              tag: "0.11.5"
              pullPolicy: "Always"
            replicaCount: 1
            envFrom:
              - secretRef:
                  name: rpc-server
            env:
              - name: "DEBUG"
                value: "rpch*"
              - name: "RESPONSE_TIMEOUT"
                value: "10000"
              - name: "DISCOVERY_PLATFORM_API_ENDPOINT"
                value: "http://staging-discovery-platform.staging:3020"
              - name: "FORCE_ZERO_HOP"
                value: true
            ingress:
              enabled: true
              className: traefik
              annotations:
                cert-manager.io/cluster-issuer: production
                traefik.ingress.kubernetes.io/router.middlewares: traefik-rate-limiting@kubernetescrd
              hosts:
                - host: rpc-server-zero-hop.staging.rpch.tech
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: rpc-server-zero-hop.staging.rpch.tech-tls
                  hosts:
                    - rpc-server-zero-hop.staging.rpch.tech
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
