apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: latency-monitor
  namespace: production
spec:
  project: production
  source:
    repoURL: https://github.com/Rpc-h/helm-charts
    targetRevision: main
    path: latency-monitor
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            service:
              port: 1234
            image:
              repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/latency-monitor
              tag: "e50a3eb"
            env:
              - name: "MONITOR_LOG_LEVEL"
                value: "0"
              - name: "MONITOR_METRICS_REQUEST_INTERVAL"
                value: "1"
              - name: "MONITOR_RPC_SERVER_ADDRESS"
                value: "http://production-rpc-server.production:8080/?exit-provider=https://primary.gnosis-chain.rpc.hoprtech.net"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
