apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: latency-monitor
  namespace: production
spec:
  groups:
    - name: latency-monitor
      rules:
        - alert: LatencyMonitorHighLatency
          annotations:
            description: >-
              10% of all successful RPCh request latencies (quantile Q90%) have been above 1.5 second for 10 minutes.
            summary: Latencies are very high.
          expr: rpch_latencies_success{quantile="0.9"} > 1.5
          for: 10m
          labels:
            severity: warning
            environment: production
        - alert: LatencyMonitorHighFailureCount
          annotations:
            description: >-
              Failed RPCh latency request count has been more than 10 for 3 minutes.
            summary: Failed latency request count is very high.
          expr: increase(rpch_latencies_failure_count[60s]) > 10
          for: 3m
          labels:
            severity: critical
            environment: production