apiVersion: hoprnet.org/v1alpha
kind: Hoprd
metadata:
  name: hoprd-node-4
  namespace: staging
spec:
  config:
    autoRedeemTickets: true
    announce: false
  enabled: true
  environmentName: monte_rosa
  ingress:
    enabled: true
  monitoring:
    enabled: true
  secret:
    secretName: hoprd-node-4
  version: riga