apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-operator
  namespace: production-operator
spec:
  encryptedData:
    PRIVATE_KEY: AgA2kAxvvn3R0C8Rst7uUc3bGp55w4gUsb0uxNldqvZz5V9XtPT2c36r0IA7l7Qbnf5sP8uHbvgQC4vgcOZ6T3RVD8L5Ksy+xp/8uphveqSdxRJ5DFEipsG8Ti8MKtxgWLkEM2hETzlxrmtEIUCA034D8NSm/xPFdjC0IiP55ODrBrswa5gFt+W217dAx6YCLo75yUW2OzW4iOxOhXusn4jHOE2ce37pd8ahKb0EfaO3tbwQpCVaAy7sjfyCcptHFUgb1TCA4ILheXwbj9gnLNCW6u2HQSa80MCtx3i5T2H/Menxu5ZB666ZE45HNe/nZuNxzuQvdGa+jckyhhTP4kHDjZNlkuZga4xLtIR/f8Uf5YtI290YZlfUkGp4CRiXVQ0VBBzeUK1DfVjG7qk4CWhPX0N0KnubKS/e4CAontGxKoXqvHBhvAkjHg4HFOTT2OiHgsJxpA0Ty0WAko29IwABz+z9dYW6+s1zunltIb39rL1080UVvHRsaAs5cQwMuyvS3YEjVuJ0R8Om6dwAPv7mWomyMyKv+M5NkggR0zAFIR0Ieqnc8EDNhR3QslA8W6R4I5XNyErMCkUNP6aPEiifpsKPN41bUGU5v8btsE6d+g02bub56mC1yTQlpncUg8rQgYU78PoXDyhV0u5Sdw7FH3N8U1np1mC47RoHTP8al3o0OhQNKumBI33/FcE1mny4mPIEdezcOVLEp6kkvDY3/a6VIbI6Y2R+FHedIuXMKiieIlN1EtGyFR40n3DHLRSgAJr6H9v2B81nWvW0kQnoL5Y=
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-operator
      namespace: production-operator