apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manager
  namespace: staging
spec:
  project: staging
  source:
    #TODO - do not hardcode
    repoURL: https://github.com/Rpc-h/helm-charts
    targetRevision: main
    path: manager
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/rpch-375921/rpch/manager
              tag: "0202e3b"
            envFrom:
              - type: secret
                name: manager
            env:
              - name: "PORT"
                value: "3030"
              - name: "DEBUG"
                value: "rpch*"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
