apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: manager
  namespace: staging
spec:
  encryptedData:
    DP_SECRET: AgA0r12zl8ajWzJ2mLf0Kufcml0gYySJ2HopzTECSW3r8bWhJpK8UGGN+sJCRLslK3i66wTCw19eoXDVsf+8qpP4ijKTlat8vxEJL81Kj4lqOpGItFDEbOdKD8wHMHsWX1As/GJuW6j/KhLfOwoQSNBwNIi1PDc4jlia72W0h4r8pKVabrqq6n5UjU6+QvZlPqGULT7aNQ4DinFz+wTbGdl+EOSxCPak3YjT1FovLhsLZtkPz8+PG2ddeKkk8qlO9gQCw/6rH4bco5+8AMl+OXrbHtYMzG/42p6+vB/UDXeX7bCgaOQ54tiRC6rMjZ4UnHit3m/YT2C9sQyqBnbKaDdxmgkiutnNKmxOuWWuMHbnFKJhaS/ditQdt3PvEjnJizHGZCKeaCXfLTEu20/fkJq72JhF25S9aBHvXPOsOw8AmO/oJvOv34WszohP94FIw4QKxHwVJuhZZkRTvV9O4bbTyjAxf9drw803rP/kwLzot3ArFE1SaAnjYQ0gKWNsqN4HHC/qwmOTFv1hGOJSTegWCTcTfRvbEwqRQkUx1psLcsdHNqB7BJhyzKJEOpaQV641+lgKk7Zarm0WFHibpS+SB3uxQqR+iDqc7YE4tEhqpJGoA5T6jQhiYZQxWLuzFLbbO5rrwU1N72+Pv0sFkETbJHN7eS2BXHdAokmorZjeKnVM6zbQw31ZfJq1f891ZwwkCrkCKXSxC1j/5uI=
  template:
    metadata:
      creationTimestamp: null
      name: manager
      namespace: staging
    type: Opaque